name: App build

on:
  workflow_dispatch:

jobs:
  macos-build:
    name: App build
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 6
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Build extension
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm build
      - name: Xcode build
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: ./GitHub One Monokai.xcodeproj
          destination: platform=macOS
          target: GitHub One Monokai
          action: build
      - name: Prepare artifact
        run: |
          mkdir -p "bin/GitHub One Monokai"
          mv "build/Release/GitHub One Monokai.app" "bin/GitHub One Monokai"
          chmod a+x "bin/GitHub One Monokai/GitHub One Monokai.app/Contents/MacOS/GitHub One Monokai"
          ln -s /Applications "bin/GitHub One Monokai/Applications"
          hdiutil create bin/tmp.dmg -ov -volname "GitHub One Monokai" -fs HFS+ -srcfolder "bin/GitHub One Monokai"
          hdiutil convert bin/tmp.dmg -format UDZO -o "bin/GitHub One Monokai.dmg"
          rm bin/tmp.dmg
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: GitHub One Monokai
          path: bin/GitHub One Monokai.dmg
